config/routes.rb
ContactForm::Application.routes.draw do
  devise_for :users
  resources :cforms

  root 'cforms#index'

end

app/models/cform.rb
class Cform < ActiveRecord::Base

  validates :first_name, presence: true, format: { with: /\w[a-z]+\z/i }
  validates :last_name, presence: true, format: { with: /\w[a-z]+\z/i }
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }, uniqueness: true
  validates :subject, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  roles = %w(admin viewer)
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :role, presence: true, inclusion: {in: roles, message: "must be an admin or a viewer"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/cforms_controller.rb
class CformsController < ApplicationController
  before_action :set_cform, only: [:show, :edit, :update, :destroy]

  # GET /cforms
  # GET /cforms.json
  def index
    @user = current_user
    if @user[:role] == "viewer"
      redirect_to action: 'new'
    end
    @cforms = Cform.all
  end

  # GET /cforms/1
  # GET /cforms/1.json
  def show
    @user = current_user
    if @user[:role] == "viewer"
      redirect_to action: 'new', notice: 'Cform was successfully created.'
    end
  end

  # GET /cforms/new
  def new
    @cform = Cform.new
  end

  # GET /cforms/1/edit
  def edit
  end

  # POST /cforms
  # POST /cforms.json
  def create
    @cform = Cform.new(cform_params)

    respond_to do |format|
      if @cform.save
        format.html { redirect_to @cform, notice: 'Cform was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cform }
      else
        format.html { render action: 'new' }
        format.json { render json: @cform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cforms/1
  # PATCH/PUT /cforms/1.json
  def update
    respond_to do |format|
      if @cform.update(cform_params)
        format.html { redirect_to @cform, notice: 'Cform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cforms/1
  # DELETE /cforms/1.json
  def destroy
    @cform.destroy
    respond_to do |format|
      format.html { redirect_to cforms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cform
      @cform = Cform.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def cform_params
      params.require(:cform).permit(:email, :subject, :description, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cforms_helper.rb
module CformsHelper
end

app/views/cforms/_form.html.erb
<%= form_for(@cform) do |f| %>
  <% if @cform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cform.errors.count, "error") %> prohibited this cform from being saved:</h2>

      <ul>
      <% @cform.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit :"Create Form" %>
  </div>
<% end %>

app/views/cforms/edit.html.erb
<h1>Editing cform</h1>

<%= render 'form' %>

<%= link_to 'Show', @cform %> |
<%= link_to 'Back', cforms_path %>

app/views/cforms/index.html.erb
<h1>Listing cforms</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Subject</th>
      <th>Description</th>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cforms.each do |cform| %>
      <tr>
        <td><%= cform.email %></td>
        <td><%= cform.subject %></td>
        <td><%= cform.description %></td>
        <td><%= cform.first_name %></td>
        <td><%= cform.last_name %></td>
        <td><%= link_to 'Show', cform %></td>
        <td><%= link_to 'Edit', edit_cform_path(cform) %></td>
        <td><%= link_to 'Destroy', cform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cform', new_cform_path %>

app/views/cforms/new.html.erb
<h1>New cform</h1>

<%= render 'form' %>

<%= link_to 'Back', cforms_path %>

app/views/cforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @cform.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @cform.subject %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cform.description %>
</p>

<p>
  <strong>First name:</strong>
  <%= @cform.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @cform.last_name %>
</p>

<%= link_to 'Edit', edit_cform_path(@cform) %> |
<%= link_to 'Back', cforms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactForm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

          <% if user_signed_in? %>

            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li> <%= link_to "Register", new_user_registration_path %></li>
            <li> <%= link_to "Log In", new_user_session_path %></li>
          <% end %>


       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>